"""
Django settings for firstpjt project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-v_=8(dib1tu&%_8l+5bzpk*9)-v(g#!x31(2f5fxtb(+1hqa^!"
API_BEARER_TOKEN = "your_token_here"
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

import os

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
# Application definition

INSTALLED_APPS = [
    "articles",
    "adminpage",
    "rest_framework",
    "rest_framework.authtoken",
    "drf_yasg",
    "django_extensions",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "django_apscheduler",  # ★ apscheduler 추가
]



# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework.authentication.TokenAuthentication',  # 토큰 인증 설정
#     ),
#     'DEFAULT_PERMISSION_CLASSES': (
#         'rest_framework.permissions.IsAuthenticated',  # 기본 권한은 인증된 사용자만 허용
#     ),
# }




MIDDLEWARE = [
    ##테스트 용
    'corsheaders.middleware.CorsMiddleware', 
    ##웹 테스트 용
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]
# 개발환경에서 모든 출처 허용 (추후 배포시 도메인 명시 권장)
CORS_ALLOW_ALL_ORIGINS = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'i13d201.p.ssafy.io']

ROOT_URLCONF = "firstpjt.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "firstpjt.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


def get_env_variable(var_name):
    try:
        return os.environ[var_name]
    except KeyError:
        raise ImproperlyConfigured(f"환경 변수에서 {var_name}를 찾을 수 없습니다. .env 파일을 확인해주세요.")

MYSQL_PASSWORD = get_env_variable("MYSQL_PASSWORD")
OPENAI_API_KEY = get_env_variable("OPENAI_API_KEY")
##s3
AWS_ACCESS_KEY_ID = get_env_variable("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = get_env_variable("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = 'sanggyeonrye'
AWS_S3_REGION_NAME = 'ap-northeast-2'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # MySQL 사용
        'NAME': 'sanggyeonrye',          # 실제 MySQL 데이터베이스 이름
        'USER': 'levelup',         # MySQL 사용자명
        'PASSWORD':  get_env_variable("MYSQL_PASSWORD"),
        'HOST': 'i13d201.p.ssafy.io',                    # MySQL 서버 주소 (로컬: 'localhost' 또는 '127.0.0.1')
        'PORT': '3306',                         # MySQL 기본 포트
        'CONN_MAX_AGE': 120
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = False

CSRF_TRUSTED_ORIGINS = [
    'https://i13d201.p.ssafy.io',
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY") 
if not OPENAI_API_KEY:
    raise ImproperlyConfigured("환경 변수에서 OPENAI_API_KEY를 찾을 수 없습니다. .env 파일을 확인해주세요.")

OPENAI_BASE_URL = "https://gms.ssafy.io/gmsapi/api.openai.com/v1"
# 디버깅용 print는 실제 운영에서는 제거하는 것이 좋습니다.
# print("DEBUG OPENAI KEY:", OPENAI_API_KEY)



# 허용할 최대 업로드 크기 (예: 20MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024  # 20MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 20 * 1024 * 1024  # 20MB

print("DEBUG: settings loaded with CORS_ALLOW_ALL_ORIGINS =", CORS_ALLOW_ALL_ORIGINS)