pipeline {
    agent any

    stages {
        stage('Print Message') {
            steps {
                script {
                    echo '✅ This should appear in the Console Outㄴㅇㄹput!!'
                }
            }
        }
    }
}